name: Restrict Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  check-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the pusher is allowed
        run: |
          if [[ "${{ github.actor }}" != "innekto" ]]; then
            echo "❌ You are not allowed to push to dev!";
            exit 1;
          fi
